services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=docker
    volumes:
      - /srv/plex:/config
      - nfsmedia:/media
    restart: unless-stopped
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped


volumes:
  nfsmedia:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.3,nfsvers=4
      device: ":/volume1/Media/"
